; Kloset store definition for a Backblaze B2 bucket

[byte]
location          = b2://s3.us-west-004.backblazeb2.com/YOUR-BUCKET-NAME
access_key        = YOUR_B2_KEY_ID
secret_access_key = YOUR_B2_APPLICATION_KEY
region            = us-west-004
use_tls           = true
